---
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]


env:
  PROJECT_ID: maya-02
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: maya-cluster    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: maya-gke-test # TODO: update to deployment name
  REPOSITORY: images # TODO: update to Artifact Registry docker repository
  IMAGE: maya-service

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml



      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/maya-02/locations/global/workloadIdentityPools/github-identity-pool/providers/github-provider'
          service_account: ' maya-service-account@maya-02.iam.gserviceaccount.com'
          #https://iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID