---
name: Build and Push Spring boot App Image to Google Cloud Platform

on:
  push:
    branches: [ "master" ]

jobs:
  MVN_BUILD_AND_DOCKER_BUILD_AND_PUBLISG_TO_GCR:
    runs-on: ubuntu-latest
    name: A job to build and push docker TO GC repository
  env:
    IMAGE_NAME: maya-core
    PROJECT_ID: maya-355709
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Buildx with googe cred
        uses: google-github-action/setup-gcloud@master
        with:
          service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
          project_id: ${{env.PROJECT_ID}}
          export_default_credentials: true

      - name:  Build Docker image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker client
        run: gcloud auth configure-docker --quite

      - name: Push docker image to container registry
        run: docker tag maya-core:latest gcr.io/$PROJECT_ID/maya-core:latest
          docker push maya-core:latest gcr.io/$PROJECT_ID/maya-core:latest